// Code generated by mockery v2.20.0. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockPaymentsEventsVisitor is an autogenerated mock type for the PaymentsEventsVisitor type
type MockPaymentsEventsVisitor struct {
	mock.Mock
}

// VisitWithdrawalCreated provides a mock function with given fields: withdrawalCreated
func (_m *MockPaymentsEventsVisitor) VisitWithdrawalCreated(withdrawalCreated WithdrawalCreated) error {
	ret := _m.Called(withdrawalCreated)

	var r0 error
	if rf, ok := ret.Get(0).(func(WithdrawalCreated) error); ok {
		r0 = rf(withdrawalCreated)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockPaymentsEventsVisitor interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPaymentsEventsVisitor creates a new instance of MockPaymentsEventsVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPaymentsEventsVisitor(t mockConstructorTestingTNewMockPaymentsEventsVisitor) *MockPaymentsEventsVisitor {
	mock := &MockPaymentsEventsVisitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
