// Code generated by mockery v2.14.0. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockEventsHandler is an autogenerated mock type for the EventsHandler type
type MockEventsHandler struct {
	mock.Mock
}

// HandleEvent provides a mock function with given fields: event
func (_m *MockEventsHandler) HandleEvent(event interface{}) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockEventsHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEventsHandler creates a new instance of MockEventsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEventsHandler(t mockConstructorTestingTNewMockEventsHandler) *MockEventsHandler {
	mock := &MockEventsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
