// Code generated by mockery v2.42.2. DO NOT EDIT.

package events

import mock "github.com/stretchr/testify/mock"

// MockDeserializer is an autogenerated mock type for the Deserializer type
type MockDeserializer[Visitor interface{}] struct {
	mock.Mock
}

type MockDeserializer_Expecter[Visitor interface{}] struct {
	mock *mock.Mock
}

func (_m *MockDeserializer[Visitor]) EXPECT() *MockDeserializer_Expecter[Visitor] {
	return &MockDeserializer_Expecter[Visitor]{mock: &_m.Mock}
}

// Deserialize provides a mock function with given fields: rawEvent
func (_m *MockDeserializer[Visitor]) Deserialize(rawEvent []byte) (Event[Visitor], error) {
	ret := _m.Called(rawEvent)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 Event[Visitor]
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (Event[Visitor], error)); ok {
		return rf(rawEvent)
	}
	if rf, ok := ret.Get(0).(func([]byte) Event[Visitor]); ok {
		r0 = rf(rawEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Event[Visitor])
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(rawEvent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeserializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockDeserializer_Deserialize_Call[Visitor interface{}] struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - rawEvent []byte
func (_e *MockDeserializer_Expecter[Visitor]) Deserialize(rawEvent interface{}) *MockDeserializer_Deserialize_Call[Visitor] {
	return &MockDeserializer_Deserialize_Call[Visitor]{Call: _e.mock.On("Deserialize", rawEvent)}
}

func (_c *MockDeserializer_Deserialize_Call[Visitor]) Run(run func(rawEvent []byte)) *MockDeserializer_Deserialize_Call[Visitor] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockDeserializer_Deserialize_Call[Visitor]) Return(_a0 Event[Visitor], _a1 error) *MockDeserializer_Deserialize_Call[Visitor] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeserializer_Deserialize_Call[Visitor]) RunAndReturn(run func([]byte) (Event[Visitor], error)) *MockDeserializer_Deserialize_Call[Visitor] {
	_c.Call.Return(run)
	return _c
}

// NewMockDeserializer creates a new instance of MockDeserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeserializer[Visitor interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeserializer[Visitor] {
	mock := &MockDeserializer[Visitor]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
